"""empty message

Revision ID: b99a8ff4cbfe
Revises: d66f086b258
Create Date: 2017-11-18 15:59:43.744758

"""

# revision identifiers, used by Alembic.
revision = 'b99a8ff4cbfe'
down_revision = 'd66f086b258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
